TEST:
    model: resnet18_sparse
    N: 16
    M: 16
    workers: 1
    batch_size: 64
    world_size: 1
    weight_decay: 0.00005
    decay:  0.0005
    print_freq: 5
    num_classes: 10
    data: /kaggle/input/cifar-usd/CIFAR10
    val_root: /kaggle/input/cifar-usd/CIFAR10/test_img/
    val_source: /kaggle/input/cifar-usd/CIFAR10/val.txt